### ISSUE TITLE
i18n module

### ISSUE THREAD

**Issue by telco2011** [everisARQ/keystonejs-portal#11]
Make keystonejs-portal international ;-)

**Comment by ArnauAregall** [comment]
:+1: 

I've used the npm module `i18n` which is lightweight, literals are defined in JSON files, and supports object notation which is really convenient and helpful for maintaining a high number of translations organized by page or application feature.

Take a look; https://www.npmjs.com/package/i18n

**Comment by telco2011** [comment]
Looks good :+1:

**Comment by ArnauAregall** [comment]
Yestarday evening I was just playing around with `i18n` on our project, and saw this recent PR keystonejs/keystone/pull/2096 which adds multilanguage support to keystone. 

Although, AFAIK an i18n API implementation is needed anyway.

**Comment by telco2011** [comment]
Go on!!! :smirk:

**Comment by ArnauAregall** [comment]
Please see PR #31

**Comment by telco2011** [comment]
PR #31 merged.
