### ISSUE TITLE
Add responsive design for mobile phones and tablets

### ISSUE THREAD

**Issue by ardiadrianadri** [everisARQ/keystonejs-portal#12]
The app should have a different view depending of the screen resolution

**Comment by telco2011** [comment]
The default template of keystonejs is responsive because it use bootstrap. Also, you can take a look the branch https://github.com/everisARQ/keystonejs-portal/tree/feature/jumbotron-template with a new material bootstrap template concept, it's responsive too :wink:

**Comment by ardiadrianadri** [comment]
Ok, I close the issue.
